from enum import Enum


class Role(str, Enum):
    CITIZEN = "citizen"
    FIELD_RESPONDER = "field_responder"
    INCIDENT_COMMANDER = "incident_commander"
    MEDICAL_COORDINATOR = "medical_coordinator"
    SHELTER_COORDINATOR = "shelter_coordinator"
    COMMUNICATIONS_OPERATOR = "communications_operator"
    FIELD_GATEWAY_OPERATOR = "field_gateway_operator"
    GOVERNMENT_OFFICER = "government_officer"
    ANALYST_PLANNER = "analyst_planner"
    SYSTEM_ADMINISTRATOR = "system_administrator"


class Priority(str, Enum):
    CRITICAL = "critical"
    HIGH = "high"
    NORMAL = "normal"
    LOW = "low"


class VerificationStatus(str, Enum):
    VERIFIED = "VERIFIED"
    CORROBORATED = "CORROBORATED"
    UNVERIFIED = "UNVERIFIED"
    CONTRADICTORY = "CONTRADICTORY"
    STALE = "STALE"
    PREDICTED = "PREDICTED"


class ConnectivityState(str, Enum):
    CONNECTED = "CONNECTED"
    DEGRADED = "DEGRADED"
    LOCAL_ONLY = "LOCAL_ONLY"
    MESH_ONLY = "MESH_ONLY"
    SATELLITE_BACKHAUL = "SATELLITE_BACKHAUL"
    ISOLATED = "ISOLATED"


class SyncState(str, Enum):
    SYNCING = "SYNCING"
    SYNCED = "SYNCED"
    CONFLICT = "CONFLICT"
    STALE = "STALE"
    QUEUED = "QUEUED"


class MissionStatus(str, Enum):
    PROPOSED = "proposed"
    APPROVED = "approved"
    REJECTED = "rejected"
    DISPATCHED = "dispatched"
    ACCEPTED_BY_RESPONDER = "accepted_by_responder"
    DECLINED = "declined"
    EN_ROUTE = "en_route"
    ON_SCENE = "on_scene"
    COMPLETED = "completed"
    FAILED = "failed"


MISSION_TRANSITIONS = {
    MissionStatus.PROPOSED: [MissionStatus.APPROVED, MissionStatus.REJECTED],
    MissionStatus.APPROVED: [MissionStatus.DISPATCHED],
    MissionStatus.DISPATCHED: [MissionStatus.ACCEPTED_BY_RESPONDER, MissionStatus.DECLINED],
    MissionStatus.ACCEPTED_BY_RESPONDER: [MissionStatus.EN_ROUTE, MissionStatus.FAILED],
    MissionStatus.EN_ROUTE: [MissionStatus.ON_SCENE, MissionStatus.FAILED],
    MissionStatus.ON_SCENE: [MissionStatus.COMPLETED, MissionStatus.FAILED],
    MissionStatus.DECLINED: [MissionStatus.DISPATCHED],
    MissionStatus.REJECTED: [],
    MissionStatus.COMPLETED: [],
    MissionStatus.FAILED: [],
}

MISSION_TRANSITION_EVENT = {
    MissionStatus.APPROVED: "MISSION_APPROVED",
    MissionStatus.REJECTED: "MISSION_REJECTED",
    MissionStatus.DISPATCHED: "MISSION_DISPATCHED",
    MissionStatus.ACCEPTED_BY_RESPONDER: "MISSION_ACCEPTED",
    MissionStatus.DECLINED: "MISSION_DECLINED",
    MissionStatus.EN_ROUTE: "MISSION_EN_ROUTE",
    MissionStatus.ON_SCENE: "MISSION_ON_SCENE",
    MissionStatus.COMPLETED: "MISSION_COMPLETED",
    MissionStatus.FAILED: "MISSION_FAILED",
}


class EventType(str, Enum):
    RESCUE_REQUEST_CREATED = "RESCUE_REQUEST_CREATED"
    HAZARD_REPORTED = "HAZARD_REPORTED"
    INCIDENT_CREATED = "INCIDENT_CREATED"
    INCIDENT_UPDATED = "INCIDENT_UPDATED"
    INCIDENT_STATUS_CHANGED = "INCIDENT_STATUS_CHANGED"
    REQUEST_VERIFIED = "REQUEST_VERIFIED"
    REQUEST_PRIORITIZED = "REQUEST_PRIORITIZED"
    REQUEST_CANCELLED = "REQUEST_CANCELLED"
    RESOURCE_STATUS_CHANGED = "RESOURCE_STATUS_CHANGED"
    ALLOCATION_PROPOSED = "ALLOCATION_PROPOSED"
    MISSION_PROPOSED = "MISSION_PROPOSED"
    MISSION_APPROVED = "MISSION_APPROVED"
    MISSION_REJECTED = "MISSION_REJECTED"
    MISSION_DISPATCHED = "MISSION_DISPATCHED"
    MISSION_ACCEPTED = "MISSION_ACCEPTED"
    MISSION_DECLINED = "MISSION_DECLINED"
    MISSION_EN_ROUTE = "MISSION_EN_ROUTE"
    MISSION_ON_SCENE = "MISSION_ON_SCENE"
    MISSION_COMPLETED = "MISSION_COMPLETED"
    MISSION_FAILED = "MISSION_FAILED"
    HOSPITAL_CAPACITY_CHANGED = "HOSPITAL_CAPACITY_CHANGED"
    SHELTER_CAPACITY_CHANGED = "SHELTER_CAPACITY_CHANGED"
    GATEWAY_ONLINE = "GATEWAY_ONLINE"
    GATEWAY_OFFLINE = "GATEWAY_OFFLINE"
    SATELLITE_CONNECTED = "SATELLITE_CONNECTED"
    SATELLITE_DISCONNECTED = "SATELLITE_DISCONNECTED"
    MESSAGE_QUEUED = "MESSAGE_QUEUED"
    MESSAGE_SENT = "MESSAGE_SENT"
    MESSAGE_DELIVERY_CONFIRMED = "MESSAGE_DELIVERY_CONFIRMED"
    MESSAGE_DELIVERY_FAILED = "MESSAGE_DELIVERY_FAILED"
    MESSAGE_EXPIRED = "MESSAGE_EXPIRED"
    AI_RECOMMENDATION_DRAFTED = "AI_RECOMMENDATION_DRAFTED"
    AI_RECOMMENDATION_BLOCKED = "AI_RECOMMENDATION_BLOCKED"
    AI_RECOMMENDATION_APPROVED_FOR_HUMAN_REVIEW = "AI_RECOMMENDATION_APPROVED_FOR_HUMAN_REVIEW"
    APPROVAL_GRANTED = "APPROVAL_GRANTED"
    APPROVAL_REJECTED = "APPROVAL_REJECTED"
    APPROVAL_CONFLICT_DETECTED = "APPROVAL_CONFLICT_DETECTED"
    DEVICE_REGISTERED = "DEVICE_REGISTERED"
    DEVICE_CREDENTIAL_REVOKED = "DEVICE_CREDENTIAL_REVOKED"
    DEVICE_KEY_ROTATED = "DEVICE_KEY_ROTATED"
    SIGNATURE_VERIFICATION_FAILED = "SIGNATURE_VERIFICATION_FAILED"
    UNAUTHORIZED_ACTION_ATTEMPT = "UNAUTHORIZED_ACTION_ATTEMPT"
    SYNC_STARTED = "SYNC_STARTED"
    SYNC_DIGEST_EXCHANGED = "SYNC_DIGEST_EXCHANGED"
    SYNC_EVENTS_REQUESTED = "SYNC_EVENTS_REQUESTED"
    SYNC_CONFLICT_DETECTED = "SYNC_CONFLICT_DETECTED"
    SYNC_COMPLETED = "SYNC_COMPLETED"
    AI_FALLBACK_ACTIVATED = "AI_FALLBACK_ACTIVATED"
    SIMULATION_STARTED = "SIMULATION_STARTED"
    SIMULATION_EVENT = "SIMULATION_EVENT"
    SIMULATION_COMPLETED = "SIMULATION_COMPLETED"


# Events that must never be accepted from an untrusted / unsigned origin.
TRUSTED_ONLY_EVENTS = {
    EventType.APPROVAL_GRANTED,
    EventType.APPROVAL_REJECTED,
    EventType.MISSION_APPROVED,
    EventType.DEVICE_CREDENTIAL_REVOKED,
}

# Conflict-resolution field classes (03_DATABASE_DESIGN synchronization semantics)
FIELD_CLASS_COUNTER = "counter"          # CRDT op-based counter
FIELD_CLASS_LWW = "last_write_wins"      # HLC-ordered LWW register
FIELD_CLASS_STATE_MACHINE = "state_machine"  # monotonic lifecycle, highest stage wins
FIELD_CLASS_APPEND_ONLY = "append_only"  # never overwritten
